LAB1:

Name: Hamna Ashraf

Student ID: 8826836



## Part A: Create a Notebook to demonstrate NumPy Operations.

### 1. Create an array that starts from the integer 1, ends at 20, incremented by 3. 

In [90]:
import numpy as np

arr = np.arange(1,20,3)
print("Array from range 1-20, step 3\n",arr)

Array from range 1-20, step 3
 [ 1  4  7 10 13 16 19]


### 2. Create a new array of shape 3 with random numbers between 0 and 1. 

In [91]:

arr_random = np.random.random(3,)
print("Random Array of shape 3 with random 0-1:\n", arr_random)


Random Array of shape 3 with random 0-1:
 [0.3863535  0.29246051 0.84702886]


### 3. Create a 2 D array [[ 10, 20, 45],[30, 12, 16],[42, 17, 56]] and perform the following operations:
<ul>
<li>Slice the 2D array to get the first two rows</li>
<li>Slice the 2D array to get the last two rows.</li>
</ul>

In [92]:
arr_2d = np.array([[10,20,45],[30,12,16],[42,17,56]])
print("First 2 rows: \n", arr_2d[:2])

print("\nLast 2 rows: \n", arr_2d[-2:])


First 2 rows: 
 [[10 20 45]
 [30 12 16]]

Last 2 rows: 
 [[30 12 16]
 [42 17 56]]


### 4. Create two 2 x 2 arrays and demonstrate how you can stack the elements vertically, horizontally, and split the arrays into smaller arrays. 

In [93]:
arr_1= np.array([[1,2],[3,4]])
arr_2 = np.array([[5,6], [7,8]])

#Horizontal Split
hstack = np.concatenate((arr_1, arr_2), axis = 1)
print("\nHorizontal Stack: \n",hstack)

#Vertical Split
vstack = np.concatenate((arr_1, arr_2), axis = 0)
print("Vertical Stack: \n",vstack)

#Splits
split_harray = np.split(hstack, 2)
print("\nHorizontal Array split into 2:\n",split_harray)

split_varray = np.split(vstack,4)
print("\nVertical Array split into 4:\n",split_varray)



Horizontal Stack: 
 [[1 2 5 6]
 [3 4 7 8]]
Vertical Stack: 
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontal Array split into 2:
 [array([[1, 2, 5, 6]]), array([[3, 4, 7, 8]])]

Vertical Array split into 4:
 [array([[1, 2]]), array([[3, 4]]), array([[5, 6]]), array([[7, 8]])]


### 5. Create two matrices 𝑋= ([[5, 7, 2], [4, 5, 6], [7, 4 , 2]]), 𝑌= ([[4, 2],[6, 2],[4, 2]] ),

<ul>
<li>
Is it possible to multiply these matrices? </li>
<li>
Demonstrate the case when it is not possible to. 
</li>
</ul>

<b>Answer:</b>

Yes, it is possible to multiply these matrices.

It is because shape of matrix X = [[5, 7, 2], [4, 5, 6], [7, 4, 2]] is '3 x 3' and Y = [[4, 2], [6, 2], [4, 2]] is '3 x 2'

The inner value for both matrices (Column of X and Row of Y) is same i.e 3, therefore, we will be able to multiply these arrays.

In [102]:
X= np.array([[5,7,2],
             [4,5,6],
             [7,4,2]]) #3x3

Y= np.array([[4,2], #3x2
             [6,2],
             [4,2]])

arr_result = np.dot(X,Y)

print(arr_result)
#There is no error while multiplying these matrices

[[70 28]
 [70 30]
 [60 26]]


<b>Case when Multiplication is not possible:</b>

Multiplication of matrices is not possible when Column of X and Row of Y are not same.

E.g: when X = [[5, 7, 2], [4, 5, 6], [7, 4, 2]], Y = [[4, 2, 3], [6, 2, 5]]

### 6. Create two arrays, 𝑥 = ([2, −1, −8]) 𝑦 = ([3, 1, −2])
<ul>
<li> Find the Shape, Number of dimensions of vector x.</li>
<li> Reshape the vector x to a matrix of size (3,1) and determine the number of dimensions after reshaping y to a matrix of (3,1)</li>
</ul>

In [95]:
x = np.array([2,-1,-8]) 
y = np.array([3,1,-2])

print(f"Shape of vector x: {x.shape} ")
print(f"Dimention of vector x: {x.ndim}")

reshaped_x = x.reshape(3,1)
reshaped_y = y.reshape(3,1)

print(f"Dimention after reshaping y: {reshaped_x.ndim}")


Shape of vector x: (3,) 
Dimention of vector x: 1
Dimention after reshaping y: 2


### How does broadcasting work?
When performing arithmatic operations, numpy expands the smaller shape to match the larger shape. It is done to make the operation possible between the two.


<b>E.g:</b>

If we take a 3 x 3 matrix X:

[[1, 3, 4]\
 [2, 5, 2]\
 [1, 2, 6]]

While performing arithematic operations "*" and "-" on Matrix X with an array x [4, 5, 6]:\
Array x is broadcasted and looks like:\
[4, 5, 6]\
[4, 5, 6]\
[4, 5, 6]

In [96]:
X =np.array([[1, 3, 4],
             [2, 5, 2],
             [1, 2, 6]])

x = np.array([4, 5, 6])

print("Multiplication:\n", (X * x))
print("\nSubtraction:\n ", (X - x))



Multiplication:
 [[ 4 15 24]
 [ 8 25 12]
 [ 4 10 36]]

Subtraction:
  [[-3 -2 -2]
 [-2  0 -4]
 [-3 -3  0]]


## Part B - Linear Equations :

Determine the singularity of the system of equations, comment on the expected solution of the system. Solve the system of equations if possible. Justify the reason why you believe the system can or cannot be solved using NumPy functions. 

<b>Answer:</b>\
To check if a matrix is singular, we check the determinent of that matrix. If |det| is 0, then matrix is singular otherwise non-singular.\
If matrix is <i>non-singluar</i> then the <i>system of equations can be solved</i>, which means there is a unique solution. If matrix is <i>singular</i> it means that are <i>infinite or no solutions</i>

### Part B.1:

In [97]:
singularity = True

X = np.array([[4, 1,-2], 
             [2,-3, 2],
             [1, 2, 3]])

det = np.linalg.det(X)
if(det==0):
    singularity = True
    print("Matrix is singular")
else:
    singularity = False
    print("Matrix is non-singular")


Matrix is non-singular


As matrix is non-singular then we can solve this system of equations using Numpy functions.



In [98]:
Y = np.array([10, -4, 6])

x, y, z = np.linalg.solve(X, Y)

print(f"x = {x}\ny = {y}\nz = {z}")

x = 1.7999999999999998
y = 2.4
z = -0.2


### Part B.2:

In [99]:
singularity = True

A = np.array([[2,-1, 3, 4], 
             [4,-2, 6, 8],
             [3, 1,-2, 2],
             [1, 3,-4, 1]])

det = np.linalg.det(X)
if(det==0):
    singularity = True
    print("Matrix is singular")
else:
    singularity = False
    print("Matrix is non-singular")

Matrix is non-singular


The Matrix A in part B.2 is singular, because the determinant came out to be 0.\
Therefore, this system of equations can not be solved with Numpy too. Singular matrix error is given if we try to solve it.\


To see the error message, uncomment the code given below.

In [100]:
# B = np.array([10, 20, 3, -1])

# x, y, z, w = np.linalg.solve(A, B)

# print(f"x = {x}\ny = {y}\nz = {z}\nw = {w}")